In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv("train.csv")
test= pd.read_csv('test.csv')

In [3]:
gender_submission=pd.read_csv('gender_submission.csv') 

In [4]:
#replacing null values
train['Age'].fillna(train['Age'].mean(),inplace=True)
test['Age'].fillna(test['Age'].mean(),inplace=True)
test['Fare'].fillna(test['Fare'].mean(),inplace=True)
train['Embarked'].fillna(value='S',inplace=True)

In [5]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare Cabin Embarked  
0        1      0         A/5 21171   7.2500   NaN        S  
1        1      0          PC 17599  71.2833   C85        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S  
3        1      0            113803  53.1000  C123        S  
4        0      0            373450   8.0500   NaN        S  
..     ...    ...               ...      ...   ...      ...  
886      0      0            211536  13.0000   NaN        S  
887      0      0            112053  30.0000   B42        S  
888      1      2        W./C. 6607  23.4500   NaN        S  
889      0      0            111369  30.0000  C148        C  
890      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:
test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex       Age  SibSp  Parch              Ticket      Fare Cabin  \
0      male  34.50000      0      0              330911    7.8292   NaN   
1    female  47.00000      1      0              363272    7.0000   NaN   
2      male  62.00000      0      0              240276    9.6875   NaN   
3      male  27.00000      0      0              315154    8.6625   NaN   
4    female  22.00000      1      1             3101298   12.2875   NaN   
..      ...       ...    ...    ...                 ...       ...   ...   
413    male  30.27259      0      0           A.5. 3236    8.0500   NaN   
414  female  39.00000      0      0            PC 17758  108.9000  C105   
415    male  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN   
416    male  30.27259      0      0              359309    8.0500   NaN   
417    male  30.27259      1      1                2668   22.3583   NaN   

    Embarked  
0          Q  
1          S  
2          Q  
3          S  
4          S  
..       ...  
413        S  
414        C  
415        S  
416        S  
417        C  

[418 rows x 11 columns]

In [7]:
train['family']=train['SibSp']+train['Parch']+1
test['family']=test['SibSp']+train['Parch']+1

In [8]:
#encoding categorical data
train['Sex'] = train['Sex'].replace(['female','male'],[0,1])
train['Embarked'] = train['Embarked'].replace(['S','Q','C'],[1,2,3])

test['Sex'] = test['Sex'].replace(['female','male'],[0,1])
test['Embarked'] = test['Embarked'].replace(['S','Q','C'],[1,2,3])

In [9]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1   
2                               Heikkinen, Miss. Laina    0  26.000000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1   
4                             Allen, Mr. William Henry    1  35.000000      0   
..                                                 ...  ...        ...    ...   
886                              Montvila, Rev. Juozas    1  27.000000      0   
887                       Graham, Miss. Margaret Edith    0  19.000000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1   
889                              Behr, Mr. Karl Howell    1  26.000000      0   
890                                Dooley, Mr. Patrick    1  32.000000      0   

     Parch            Ticket     Fare Cabin  Embarked  family  
0        0         A/5 21171   7.2500   NaN         1       2  
1        0          PC 17599  71.2833   C85         3       2  
2        0  STON/O2. 3101282   7.9250   NaN         1       1  
3        0            113803  53.1000  C123         1       2  
4        0            373450   8.0500   NaN         1       1  
..     ...               ...      ...   ...       ...     ...  
886      0            211536  13.0000   NaN         1       1  
887      0            112053  30.0000   B42         1       1  
888      2        W./C. 6607  23.4500   NaN         1       4  
889      0            111369  30.0000  C148         3       1  
890      0            370376   7.7500   NaN         2       1  

[891 rows x 13 columns]

In [10]:
test

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James    1   
1            893       3              Wilkes, Mrs. James (Ellen Needs)    0   
2            894       2                     Myles, Mr. Thomas Francis    1   
3            895       3                              Wirz, Mr. Albert    1   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    0   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf    1   
414         1306       1                  Oliva y Ocana, Dona. Fermina    0   
415         1307       3                  Saether, Mr. Simon Sivertsen    1   
416         1308       3                           Ware, Mr. Frederick    1   
417         1309       3                      Peter, Master. Michael J    1   

          Age  SibSp  Parch              Ticket      Fare Cabin  Embarked  \
0    34.50000      0      0              330911    7.8292   NaN         2   
1    47.00000      1      0              363272    7.0000   NaN         1   
2    62.00000      0      0              240276    9.6875   NaN         2   
3    27.00000      0      0              315154    8.6625   NaN         1   
4    22.00000      1      1             3101298   12.2875   NaN         1   
..        ...    ...    ...                 ...       ...   ...       ...   
413  30.27259      0      0           A.5. 3236    8.0500   NaN         1   
414  39.00000      0      0            PC 17758  108.9000  C105         3   
415  38.50000      0      0  SOTON/O.Q. 3101262    7.2500   NaN         1   
416  30.27259      0      0              359309    8.0500   NaN         1   
417  30.27259      1      1                2668   22.3583   NaN         3   

     family  
0       1.0  
1       2.0  
2       1.0  
3       1.0  
4       2.0  
..      ...  
413     1.0  
414     1.0  
415     1.0  
416     2.0  
417     4.0  

[418 rows x 12 columns]

In [11]:
X_train=train.drop(columns=['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Survived'])
X_train=X_train.iloc[:,:].values
X_train

array([[ 3.        ,  1.        , 22.        ,  7.25      ,  1.        ,
         2.        ],
       [ 1.        ,  0.        , 38.        , 71.2833    ,  3.        ,
         2.        ],
       [ 3.        ,  0.        , 26.        ,  7.925     ,  1.        ,
         1.        ],
       ...,
       [ 3.        ,  0.        , 29.69911765, 23.45      ,  1.        ,
         4.        ],
       [ 1.        ,  1.        , 26.        , 30.        ,  3.        ,
         1.        ],
       [ 3.        ,  1.        , 32.        ,  7.75      ,  2.        ,
         1.        ]])

In [12]:
y_train=train[['Survived']]
y_train=y_train.iloc[:,:].values
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [24]:
X_test=test.drop(columns=['PassengerId','Name','SibSp','Parch','Ticket','Cabin'])
X_test=X_test.iloc[:,:].values
X_test

array([[ 3.        ,  1.        , 34.5       ,  7.8292    ,  2.        ,
         1.        ],
       [ 3.        ,  0.        , 47.        ,  7.        ,  1.        ,
         2.        ],
       [ 2.        ,  1.        , 62.        ,  9.6875    ,  2.        ,
         1.        ],
       ...,
       [ 3.        ,  1.        , 38.5       ,  7.25      ,  1.        ,
         1.        ],
       [ 3.        ,  1.        , 30.27259036,  8.05      ,  1.        ,
         2.        ],
       [ 3.        ,  1.        , 30.27259036, 22.3583    ,  3.        ,
         4.        ]])

In [14]:
y_test=gender_submission.drop(columns=['PassengerId'])
y_test=y_test.iloc[:,:].values
y_test

array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [15]:
#using svc, getting 100% acc on test set but low on training set
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=42)
classifier.fit(X_train,y_train.ravel())
y_pred = classifier.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
print("Accuracy for test set-",acc*100,"%")

Accuracy for test set- 100.0 %


In [17]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[266,   0],
       [  0, 152]], dtype=int64)

In [18]:
tp=cm[0][0]
fp=cm[0][1]
tn=cm[1][1]
fn=cm[1][0]
precision=tp/(tp+fp)
precision

1.0

In [19]:
recall=tp/(tp+fn)
recall

1.0

In [20]:
#F1 = 2 * (precision * recall) / (precision + recall)
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, zero_division=1)

1.0

In [21]:
#csv file
kaggle_data = pd.DataFrame({'PassengerId':gender_submission.PassengerId, 'Survived':y_pred}).set_index('PassengerId')
kaggle_data.to_csv('submission_file.csv')

In [22]:
print("Please enter the following details:\n")
Pclass=int(input("Please enter 1/2/3 for your Upper/Middle/Lower socio-economic status:\n"))
Sex=int(input("Please enter 0/1 for female/male:\n"))
age=int(input("Please enter your age:\n"))
fare=int(input("Please enter your fare:\n"))
embarked=int(input("Please enter 1/2/3 for Port of Embarkation Southampton/Queenstown/Cherbourg:\n"))
family=int(input("Please enter your total family members that travelled\n"))

Please enter the following details:

Please enter 1/2/3 for your Upper/Middle/Lower socio-economic status:
;


ValueError: invalid literal for int() with base 10: ';'

In [ ]:
new_input=np.array([Pclass,Sex,age,fare,embarked,family]).reshape(1,-1)
new_output = classifier.predict(new_input)
if new_output==0:
    print("You would have not survived the Titanic journey")
else:
    print("You would have survived the Titanic journey")

In [ ]:
#visualisation to be done

In [23]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: X.shape[1] = 2 should be equal to 6, the number of features at training time